/* Compliance view: framework status derived from evidence, never from optimizer output. */
'use strict';
/* ================= Compliance ================= */
const FW=[
 {k:'rbi',name:'RBI Directions 2026',ver:'v2026.1 · effective 31 Jul 2026',tot:11,c:[5,2,2,1,1],note:'Replaces the repealed 2016 Cyber Security Framework.'},
 {k:'sebi',name:'SEBI CSCRF + CCI',ver:'2024 framework · graded by entity tier',tot:5,c:[2,1,1,1,0],note:'Shown for reference; applies only to SEBI-regulated entities.'},
 {k:'cis',name:'CIS Controls v8.1',ver:'IG2 safeguards in scope',tot:19,c:[9,4,4,0,2]},
 {k:'nist',name:'NIST CSF 2.0',ver:'Govern, Identify, Protect, Detect, Respond, Recover',tot:19,c:[8,5,3,2,1]},
 {k:'iso',name:'ISO/IEC 27001:2022',ver:'Annex A controls in scope',tot:23,c:[11,5,3,3,1]},
 {k:'dpdp',name:'DPDP Act 2023',ver:'Security safeguards & breach duties',tot:4,c:[1,1,1,1,0]},
];
const ST=[['Met','good','✓'],['Partial','warn','◐'],['Not met','crit','✕'],['Attested','info','✎'],['No evidence','info','?']];
const STCOL=['var(--good)','var(--warn)','var(--crit)','var(--ink-2)','var(--other)'];
const FWCTL={
 rbi:[['MFA for privileged and remote access',2,'Telemetry check failed: MFA off on ad-dc-01, pay-gw-01, core-lms-db','F-1311'],['Known-exploited vulnerabilities fixed within timelines',2,'4 KEV-listed findings open longer than 14 days','F-0877'],['Endpoint detection on critical servers',1,'EDR healthy on 3 of 4 applicable critical assets',''],['Backups tested and restorable',1,'core-lms-db and kyc-store backups untested in 90 days','F-1233'],['No high-risk ports exposed to the internet',0,'Check passed on all internet-facing assets',''],['24×7 security monitoring',0,'Wazuh agents reporting on 8 of 8 servers',''],['Incident reporting to RBI and CERT-In within 6 hours',3,'Attested by CISO, 12 Jun 2026; valid 12 months',''],['Asset inventory kept current',4,'CMDB last synced 42 days ago',''],['Board-approved cyber security policy',0,'Evidence: policy v4.2 approved 18 Apr 2026','']],
 sebi:[['Graded VAPT after major system change',1,'Last VAPT predates the payments gateway upgrade',''],['Security operations centre capability',0,'Wazuh SIEM with 24×7 coverage',''],['Privileged access management',2,'MFA off on 3 privileged systems','F-1311'],['Cyber resilience drill',3,'Attested, 3 Mar 2026','']],
 cis:[['6.5 Require MFA for administrative access',2,'MFA off on ad-dc-01, pay-gw-01','F-1311'],['7.3 Automated OS patch management',1,'2 critical assets behind patch level','F-0955'],['7.7 Remediate detected vulnerabilities',2,'KEV-listed findings open','F-0877'],['3.3 Configure data access control lists',2,'KYC bucket allows public listing','F-1390'],['11.2 Automated backups',0,'Nightly backups on all assets',''],['11.5 Test data recovery',1,'2 assets untested in 90 days','F-1233'],['10.1 Anti-malware / EDR deployed',1,'EDR missing on 4 servers',''],['1.1 Detailed enterprise asset inventory',4,'CMDB stale (42 days)','']],
 nist:[['PR.AA-03 Users and services are authenticated',2,'MFA gaps on privileged systems','F-1311'],['ID.RA-01 Vulnerabilities are identified',0,'Greenbone and Prowler scans in scope',''],['PR.PS-02 Software is maintained and replaced',1,'Legacy Log4j service still running','F-0877'],['PR.DS-01 Data at rest is protected',2,'Unencrypted database backups','F-1233'],['DE.CM-01 Networks are monitored',0,'Wazuh network rules active',''],['RC.RP-03 Backup integrity is verified',1,'2 assets untested','F-1233'],['GV.PO-01 Policy is established',3,'Attested by CISO','']],
 iso:[['A.8.5 Secure authentication',2,'MFA gaps on privileged systems','F-1311'],['A.8.8 Management of technical vulnerabilities',2,'KEV-listed findings open','F-0877'],['A.8.13 Information backup',1,'Backups untested on 2 assets','F-1233'],['A.8.16 Monitoring activities',0,'SIEM coverage complete',''],['A.5.23 Security for cloud services',2,'Public KYC bucket','F-1390'],['A.8.7 Protection against malware',1,'EDR gaps on 4 servers',''],['A.5.9 Inventory of information assets',4,'CMDB stale','']],
 dpdp:[['Sec 8(5) Reasonable security safeguards',2,'KYC documents publicly listable','F-1390'],['Sec 8(6) Breach intimation to Board and principals',3,'Attested: breach-notice runbook, 2 May 2026',''],['Data retention and erasure',1,'Retention defined; erasure not automated',''],['Encryption of personal data at rest',0,'KYC store encrypted with KMS','']],
};
let selFw='rbi';
function renderCompliance(){
  $('#fwCards').innerHTML=FW.map(f=>`<button class="fwc" data-fw="${f.k}" aria-pressed="${f.k===selFw}"><div style="display:flex;justify-content:space-between;gap:8px;align-items:baseline"><h3>${esc(f.name)}</h3><span class="mono small muted">${f.tot} controls</span></div><span class="sub">${esc(f.ver)}</span><div class="stack">${f.c.map((n,i)=>n?`<i style="width:${n/f.tot*100}%;background:${STCOL[i]}"></i>`:'').join('')}</div><div class="cnt">${f.c.map((n,i)=>n?`<span>${ST[i][2]} ${n} ${ST[i][0].toLowerCase()}</span>`:'').join('')}</div></button>`).join('');
  const f=FW.find(x=>x.k===selFw);$('#fwTitle').textContent=f.name+' · controls needing evidence review';
  $('#fwTbl').innerHTML=`<thead><tr><th>Control</th><th>Status</th><th>Evidence</th><th>Linked finding</th></tr></thead><tbody>`+FWCTL[selFw].map(r=>`<tr><td><b>${esc(r[0])}</b></td><td><span class="pill ${ST[r[1]][1]}">${ST[r[1]][2]} ${ST[r[1]][0]}</span></td><td class="small">${esc(r[2])}</td><td class="mono small">${r[3]?`${r[3]}<div class="sub">EAL ${inr(CUR_STATE.open.has(FIDX[r[3]])?CURR.mean[FIDX[r[3]]]:0)}</div>`:'—'}</td></tr>`).join('')+`</tbody>`+(f.note?`<caption style="caption-side:bottom;text-align:left;padding-top:10px" class="small muted">${esc(f.note)} Showing ${FWCTL[selFw].length} of ${f.tot} controls.</caption>`:`<caption style="caption-side:bottom;text-align:left;padding-top:10px" class="small muted">Showing ${FWCTL[selFw].length} of ${f.tot} controls.</caption>`);
  $('#penalties').innerHTML=[
   ['DPDP Act 2023: failure to take reasonable security safeguards','Up to ₹250 Cr per instance','Live exposure: public KYC bucket (F-1390)','crit'],
   ['DPDP Act 2023: failure to notify a personal data breach','Up to ₹200 Cr','Runbook attested; no open breach','info'],
   ['CERT-In Directions 2022: incident reporting','Report within 6 hours','Attested process; last drill 3 Mar 2026','info'],
   ['RBI Directions 2026: supervisory action','Monetary penalty and business restrictions','Amount is entity-specific; modelled as a declared range','warn'],
  ].map(p=>`<div class="it" style="grid-template-columns:minmax(0,1fr) auto"><span class="nm">${esc(p[0])}</span><span class="pill ${p[3]}">${p[3]==='crit'?'! Exposed':p[3]==='warn'?'Declared':'Tracked'}</span><span class="meta" style="grid-column:1/-1"><b class="mono" style="color:var(--ink)">${esc(p[1])}</b> · ${esc(p[2])}</span></div>`).join('');
}
$('#fwCards').addEventListener('click',e=>{const b=e.target.closest('[data-fw]');if(!b)return;selFw=b.dataset.fw;renderCompliance();});
