/* Data & model view: quality gates, connectors, sensitivity, lab efficacy, identity queue, conflict and assumption registers. */
'use strict';
/* ================= Data & model ================= */
function renderData(){
  const G=[['Asset count delta','10 → 10 assets (0% change, tolerance 50%)'],['No findings from unreachable scanners','All 4 reporting connectors reachable'],['Criticality present or "unknown"','13 of 13 findings evaluated'],['Provenance on every finding','connector and raw_source_id set on all findings'],['No ordinal in numeric fields','epss_score, rto_hours, rpo_hours all numeric']];
  $('#gates').innerHTML=G.map((g,i)=>`<div class="gate"><span class="pill good">✓ Pass</span><div><b>${i+1}. ${esc(g[0])}</b><div class="small muted">${esc(g[1])}</div></div></div>`).join('');
  $('#gateWeeks').innerHTML=HIST.map((h,w)=>`<i class="${h.held?'bad':''} ${w===CUR?'cur':''}" title="${wdateY(w)}: ${h.held?'rejected, previous snapshot held':'committed'}"></i>`).join('');
  $('#gateNote').innerHTML=`Week of ${wdate(GATE_FAIL)}: gate 2 failed. Greenbone was unreachable but its findings were still in the candidate, so the previous snapshot stayed current.`;
  const C=[['Wazuh','SIEM · EDR','3 min ago','good','8 of 8 agents healthy'],['Greenbone','Vulnerability scan','6 days ago','good','Weekly cadence; sets figure freshness'],['Prowler','CSPM · AWS','1 day ago','good','312 checks'],['ScoutSuite','CSPM · multi-cloud','1 day ago','good','Backup and storage posture'],['CMDB','Asset inventory · criticality','42 days ago','warn','Stale: criticality uncertainty widened'],['EPSS · CISA KEV','Threat intelligence','Not connected','info','Sample values on this page'],['Nessus · nmap · IAM','Planned connectors','Not connected','info','Out of scope for this snapshot']];
  $('#connTbl').innerHTML=`<thead><tr><th>Source</th><th>Last data</th><th>Note</th></tr></thead><tbody>`+C.map(c=>`<tr><td><b>${esc(c[0])}</b><div class="sub">${esc(c[1])}</div></td><td><span class="pill ${c[3]}">${c[3]==='good'?'●':c[3]==='warn'?'◷':'○'} ${esc(c[2])}</span></td><td class="small">${esc(c[4])}</td></tr>`).join('')+'</tbody>';
  // sensitivity
  const SENS=[['Threat event frequency baseline',{tef:.5},{tef:1.5},'×0.5 to ×1.5','declared'],['Loss magnitude, critical assets',{magCrit:.6},{magCrit:1.4},'×0.6 to ×1.4','borrowed'],['MFA resistance strength',{mfa:.6},{mfa:.2},'0.6 to 0.2','declared'],['EDR resistance strength',{edr:.7},{edr:.3},'0.7 to 0.3','measured'],['Misconfiguration exploit probability',{misconfigP:.1},{misconfigP:.35},'0.10 to 0.35','declared'],['Untested-backup downtime multiplier',{rto:{untested:1.2}},{rto:{untested:2.2}},'1.2 to 2.2','declared']];
  const rs=SENS.map(s=>({n:s[0],lo:evalState(CUR_STATE,withP(s[1])).eal,hi:evalState(CUR_STATE,withP(s[2])).eal,rng:s[3],prov:s[4]})).sort((a,b)=>(b.hi-b.lo)-(a.hi-a.lo));
  const mn=Math.min(...rs.map(r=>r.lo)),mx=Math.max(...rs.map(r=>r.hi));const X=v=>(v-mn)/(mx-mn)*100;const b0=X(CURR.eal);
  $('#tornado').innerHTML=rs.map(r=>`<div class="tr2"><div><b style="font-weight:600">${esc(r.n)}</b> <span class="prov ${r.prov}">${r.prov.toUpperCase()}</span><div class="sub">${r.rng} · ${inr(r.lo,1)} to ${inr(r.hi,1)}</div></div><div class="t"><i style="left:${X(r.lo)}%;width:${b0-X(r.lo)}%;background:var(--div-lo);border-radius:3px 0 0 3px"></i><i style="left:${b0}%;width:${X(r.hi)-b0}%;background:var(--div-hi);border-radius:0 3px 3px 0"></i><span class="mid" style="left:${b0}%"></span></div></div>`).join('')+`<p class="small muted">Centre line: today's EAL of ${inr(CURR.eal)}. The top driver is ${esc(rs[0].n.toLowerCase())}, which is ${rs[0].prov}: ${rs[0].prov==='declared'?'an assumption to calibrate first.':'a sourced parameter.'}</p>`;
  // identity queue
  const Q=[['host:10.20.4.17 ↔ cloud:i-0a3f9c71e2b','Shared instance ID and hostname','0.97','good','Merged automatically'],['cloud:kyc-docs-prod ↔ CMDB AST-0192','Name and owner-tag similarity','0.72','warn','Waiting for review'],['host:10.20.8.5 ↔ host:ci-runner-02','Shared IP address only (addresses are reused)','0.41','warn','Waiting for review']];
  $('#idq').innerHTML=Q.map(q=>`<div class="it" style="grid-template-columns:minmax(0,1fr) auto"><span class="nm mono" style="font-size:12.5px">${esc(q[0])}</span><span class="pill ${q[3]}">${q[3]==='good'?'✓':'◷'} ${esc(q[4])}</span><span class="meta" style="grid-column:1/-1">${esc(q[1])} · calibrated confidence <b class="mono" style="color:var(--ink)">${q[2]}</b> · threshold 0.90</span></div>`).join('');
  const CR=[['C1','Probability vs frequency','EPSS is used as exploit probability, with a floor for KEV-listed flaws. The mapping is our own choice and is sensitivity-tested.','warn','Open'],['C2','Deterministic cascade in a stochastic model','Dependency strengths become distributions sampled per iteration.','good','Decided'],['C3','Scenarios treated as independent','Shared control-health factors link every scenario that relies on the same control.','good','Resolved'],['C4','Additive optimizer vs interdependent controls','Every candidate portfolio is re-simulated jointly; per-control benefits are never summed.','good','Resolved'],['C5','Attack-graph scalability','Scoped to a bounded subgraph around each crown-jewel asset.','info','Deferred'],['C6','Ordinal scores used in arithmetic','Ordinals may filter, never compute. Quality gate 5 enforces this.','good','Enforced']];
  $('#conflicts').innerHTML=CR.map(c=>`<div class="ci"><span class="id">${c[0]}</span><div><b>${esc(c[1])}</b><div class="small muted">${esc(c[2])}</div></div><span class="pill ${c[3]}">${esc(c[4])}</span></div>`).join('');
  const A=[['BASELINE_THREAT_EVENT_FREQUENCY','Internet-facing 0.3 / 1.2 / 4 per yr · internal 0.05 / 0.3 / 1.2','declared','Placeholder until VERIS base rates are fitted'],['Exploit probability','EPSS 30-day score; floor 0.50 if KEV-listed; unscored 0.05','borrowed','FIRST EPSS, CISA KEV'],['CONTROL_RESISTANCE · MFA','0.40','declared','Awaiting lab measurement'],['CONTROL_RESISTANCE · EDR','0.50','measured','Lab capability sweep (sample)'],['CONTROL_RESISTANCE · segmentation','0.35','declared','Expert estimate'],['Shared control health','Beta-PERT 0.55 / 0.95 / 1.00 per iteration','declared','Resolves C3 correlation'],['BASE_LOSS_MAGNITUDE · critical','₹40 L / ₹1.5 Cr / ₹12 Cr per event','borrowed','Cyentia IRIS, US-calibrated; 20–40% adjustment pending'],['RTO_MULTIPLIER','tested 1.0 · untested 1.6 · none 2.5','declared','Downtime cost per hour is a user input'],['Loss-type split per asset','e.g. payments: 45% downtime, 20% regulatory','declared','FAIR-MAM style breakdown'],['MONTE_CARLO_ITERATIONS','4,000; seed derived from snapshot content','engine','Same snapshot always gives the same figure'],['VALUE_AT_RISK_PERCENTILE','95th','declared','Board reporting convention'],['Residual exposure per asset','Exploit probability 0.06 for unknown and unscanned flaws','declared','Keeps patched assets from reading as zero risk'],['Risk appetite','₹3 Cr expected annual loss','declared','Board-approved (sample)']];
  $('#assumTbl').innerHTML=`<thead><tr><th>Assumption</th><th>Value</th><th>Provenance</th><th>Source / note</th></tr></thead><tbody>`+A.map(a=>`<tr><td class="mono small"><b>${esc(a[0])}</b></td><td class="small">${esc(a[1])}</td><td><span class="prov ${a[2]}">${a[2].toUpperCase()}</span></td><td class="small muted">${esc(a[3])}</td></tr>`).join('')+'</tbody>';
  renderLab();
}
function renderLab(){
  const el=$('#labChart');el.innerHTML='';const W=Math.max(280,el.clientWidth);const H=W<560?230:260;const m={l:44,r:14,t:12,b:32};const iw=W-m.l-m.r,ih=H-m.t-m.b;
  const off=[.22,.41,.63,.81,.91,.96],on=[.05,.12,.27,.48,.69,.84],n=400;
  const xs=l=>m.l+(l-.6)/(6.4-.6)*iw,ys=p=>m.t+ih-p*ih;
  const svg=S('svg',{viewBox:`0 0 ${W} ${H}`,height:H,role:'img','aria-label':'Attack success rate by attacker capability, EDR on and off'},el);
  const g=S('g',{class:'ax'},svg);yAxis(g,ys,[0,.25,.5,.75,1],m.l,m.l+iw,v=>pct(v));
  for(let l=1;l<=6;l++){const t=S('text',{x:xs(l),y:H-12,'text-anchor':'middle',class:'lbl'},g);t.textContent='L'+l;}
  const t2=S('text',{x:m.l+iw,y:H-1,'text-anchor':'end',class:'lbl'},g);t2.textContent='attacker capability →';
  const logit=p=>Math.log(p/(1-p));
  const fit=arr=>{let sx=0,sy=0,sxx=0,sxy=0;arr.forEach((p,i)=>{const x=i+1,y=logit(p);sx+=x;sy+=y;sxx+=x*x;sxy+=x*y;});const b=(6*sxy-sx*sy)/(6*sxx-sx*sx),a=(sy-b*sx)/6;return {a,b,f:x=>1/(1+Math.exp(-(a+b*x))),mid:-a/b};};
  const wil=(p)=>{const z=1.96,d=1+z*z/n,c=(p+z*z/(2*n))/d,h=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return [c-h,c+h];};
  const draw=(arr,col)=>{const F=fit(arr);let d='';for(let i=0;i<=50;i++){const x=.8+5.4*i/50;d+=(i?'L':'M')+xs(x)+','+ys(F.f(x));}S('path',{d,style:`fill:none;stroke:${col};stroke-width:2`},svg);
    arr.forEach((p,i)=>{const [lo,hi]=wil(p);S('line',{x1:xs(i+1),x2:xs(i+1),y1:ys(lo),y2:ys(hi),style:`stroke:${col};stroke-width:1.5`},svg);S('circle',{cx:xs(i+1),cy:ys(p),r:4,style:`fill:${col};stroke:var(--surface);stroke-width:2`},svg);});return F;};
  const Foff=draw(off,'var(--s2)'),Fon=draw(on,'var(--s1)');
  S('line',{x1:m.l,x2:m.l+iw,y1:ys(.5),y2:ys(.5),style:'stroke:var(--ink-2);stroke-width:1;opacity:.4'},svg);
  const ya=ys(.5)-7;S('line',{x1:xs(Foff.mid),x2:xs(Fon.mid),y1:ya,y2:ya,style:'stroke:var(--ink);stroke-width:1.5'},svg);
  const lb=S('text',{x:(xs(Foff.mid)+xs(Fon.mid))/2,y:ya-6,'text-anchor':'middle',class:'dlabel'},svg);lb.textContent='+'+(Fon.mid-Foff.mid).toFixed(1)+' levels';
}
